pipeline:
  build:
    image: node:8.11.3-alpine
    commands:
      - cd demo01
      - npm run-script build
      - tar czvf dist.tar dist1
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: docker
    template: >
      {{#success build.status}}
        Hello, build {{build.number}} succeeded. Good jobbb.
      {{else}}
        Sorry, build {{build.number}} failed. Fix me please.
      {{/success}}